### ISSUE TITLE
Should we add hatch to the conda instructions?

### ISSUE THREAD

**Issue by gabalafou** [Quansight-Labs/accessible-pygments#37]
When I started setting up my development environment to create PR #33, I skipped straight to the instructions for setting up a conda environment. But then when I tried to run any of the `hatch` commands for other steps in the contributing doc, I got the "command not found" error.

This seems inconsistent to me. Maybe I'm missing something, but I'm not quite sure I see the point of telling contributors they can use conda if we require them to have hatch installed first. And if we're fine with them installing and using hatch from within the conda environment, then why not add that to the instructions for setting up a conda environment?

**Comment by trallard** [comment]
🤔 were you following the instructions in the README? or the [CONTRIBUTING.md file](https://github.com/Quansight-Labs/accessible-pygments/blob/main/CONTRIBUTING.md#contributing-to-this-package)?

I have never used hatch within a conda environment as the purpose of hatch is to create virtual environments plus aid with package development and building. So that seems an anti-pattern (you can instead generate conda envs with hatch vs virtual envs).
I think I might have left the conda instructions from before adding `hatch` and moving from the `setup.py` to `pyproject.toml`but in any case I'd prefer getting rid of the conda env and its instructions.
